# ==============================================================
# = Eureka Server - Profilo peer1
# ==============================================================

server:
  port: 8761

spring:
  config:
    activate:
      on-profile: peer1
  application:
    name: EurekaServer
# ==============================================================
# = Impostazione Eureka Server
# ============================================================== 
eureka:
  instance:
    hostname: peer1
    metadataMap:
      zone: zone1
    preferIpAddress: true
    instanceId: ${spring.application.name}-1
# ==============================================================
# = Impostazione Server
# ============================================================== 
  server:
    #Abilita o disabilita l'auto preservazione
    enableSelfPreservation: false
    #Durata (in ms) della cache
    responseCacheUpdateIntervalMs: 30000
    #Tempo di attesa in ms di deregistrazione del servizio (def 60000)
    evictionIntervalTimerInMs: 30000
    #Tempo di attesa (in secondi) prima di accettare richieste
    waitTimeInMsWhenSyncEmpty: 5
# ==============================================================
# = Impostazione Client
# ============================================================== 
  client:
    serviceUrl:
      defaultZone:  http://user:BimBumBam_2018@localhost:8762/eureka/,http://user:BimBumBam_2018@localhost:8763/eureka/

# ==============================================================
# = Security Parameters
# ============================================================== 
sicurezza:
  userpwd: 'BimBumBam_2018'
  adminpwd: 'MagicaBula_2018'  
  
# ==============================================================
# = Logs Parameters
# ==============================================================        
logging:
  level:
    org:
      springframework:
        security: INFO
        cloud: DEBUG
---

# ==============================================================
# = Eureka Server - Profilo peer2
# ==============================================================

server:
  port: 8762

spring:
  config:
    activate:
      on-profile: peer2
  application:
    name: EurekaServer
# ==============================================================
# = Impostazione Eureka Server
# ============================================================== 
eureka:
  instance:
    hostname: peer2
    metadataMap:
      zone: zone2
    preferIpAddress: true
    instanceId: ${spring.application.name}-2
# ==============================================================
# = Impostazione Server
# ============================================================== 
  server:
    #Abilita o disabilita l'auto preservazione
    enableSelfPreservation: false
    #Durata (in ms) della cache
    responseCacheUpdateIntervalMs: 30000
    #Tempo di attesa in ms di deregistrazione del servizio (def 60000)
    evictionIntervalTimerInMs: 30000
    #Tempo di attesa (in secondi) prima di accettare richieste
    waitTimeInMsWhenSyncEmpty: 5
# ==============================================================
# = Impostazione Client
# ============================================================== 
  client:
    serviceUrl:
      defaultZone: http://user:BimBumBam_2018@localhost:8761/eureka/,http://user:BimBumBam_2018@localhost:8763/eureka/  

# ==============================================================
# = Security Parameters
# ============================================================== 
sicurezza:
  userpwd: 'BimBumBam_2018'
  adminpwd: 'MagicaBula_2018'  
  
# ==============================================================
# = Logs Parameters
# ==============================================================        
logging:
  level:
    org:
      springframework:
        security: INFO
        cloud: DEBUG
---

# ==============================================================
# = Eureka Server - Profilo peer3
# ==============================================================

server:
  port: 8763

spring:
  config:
    activate:
      on-profile: peer3
  application:
    name: EurekaServer
# ==============================================================
# = Impostazione Eureka Server
# ============================================================== 
eureka:
  instance:
    hostname: peer3
    metadataMap:
      zone: zone3
    preferIpAddress: true
    instanceId: ${spring.application.name}-3
# ==============================================================
# = Impostazione Server
# ============================================================== 
  server:
    #Abilita o disabilita l'auto preservazione
    enableSelfPreservation: false
    #Durata (in ms) della cache
    responseCacheUpdateIntervalMs: 30000
    #Tempo di attesa in ms di deregistrazione del servizio (def 60000)
    evictionIntervalTimerInMs: 30000
    #Tempo di attesa (in secondi) prima di accettare richieste
    waitTimeInMsWhenSyncEmpty: 5
# ==============================================================
# = Impostazione Client
# ============================================================== 
  client:
    serviceUrl:
      defaultZone: http://user:BimBumBam_2018@localhost:8761/eureka/,http://user:BimBumBam_2018@localhost:8762/eureka/  

# ==============================================================
# = Security Parameters
# ============================================================== 
sicurezza:
  userpwd: 'BimBumBam_2018'
  adminpwd: 'MagicaBula_2018'  
  
# ==============================================================
# = Logs Parameters
# ==============================================================        
logging:
  level:
    org:
      springframework:
        security: INFO
        cloud: DEBUG

# ==============================================================
# = Eureka Endpoints
# ==============================================================        
#GET /eureka/apps = visualizza i dettagli di tutte le istanze delle app registrate
#GET /eureka/apps/[appID] = visualizza i dettagli di una specifica app
#GET /eureka/apps/[appID]/[instanceID] = visualizza i dettagli di una istanza di una specifica app
#PUT /eureka/apps/[appID]/[instanceID] = Invia un heartbeat ad una specifica istanza  di una app
#DELETE /eureka/apps/[appID]/[instanceID] = Elimina una specifica istanza della app selezionata
#POST /eureka/apps/[appID] = aggiunge una istanza della app selezionata        

